name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t tesla:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker tag tesla:latest eljude03/tesla:latest && docker push eljude03/tesla:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into your homelab server
        run: |
          echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"

          # Create the SSH directory if it doesn't exist
          mkdir -p ~/.ssh
          # Set the permissions for the directory
          chmod 700 ~/.ssh
          # Write the SSH private key to the file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # Set permissions for the private key
          chmod 600 ~/.ssh/id_rsa
          # Add the host to known hosts to avoid prompts
          ssh-keyscan -H 192.168.68.119 >> ~/.ssh/known_hosts
          # SSH into the host and run a command
          ssh -o StrictHostKeyChecking=no eljude@192.168.68.119 "echo 'SSH connection successful'"

      - name: Pull and deploy Docker image
        run: |
          docker pull eljude03/tesla:latest
          docker stop tesla || true
          docker rm tesla || true
          docker run -d -p 3055:80 --name tesla eljude03/tesla:latest
